CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnr VARCHAR(10) NOT NULL UNIQUE,
    owner_email VARCHAR(255) NOT NULL,
    flight_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    seat_number VARCHAR(255) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_booking_owner ON bookings (owner_email);
